name: Pre-release

on:
  push:
    branches:
      - master

jobs:
  release_cli:
    name: "Build and release cli"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn --silent

      - name: "Build cli"
        run:
          yarn build-cli

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build of cli"
          files: |
            cli/cli.js
