name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  release_cli:
    name: "Build and release CLI"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn --silent

      - name: "Build cli"
        run:
          yarn build-cli

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Add version to the filename
        run: mv cli/cli.js cli/cli-${{ steps.get_version.outputs.version }}.js

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Development Build of cli"
          files: |
            cli/*.js
